[2024-08-25T06:06:11.604+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T06:06:11.637+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:11.105286+00:00 [queued]>
[2024-08-25T06:06:11.651+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:11.105286+00:00 [queued]>
[2024-08-25T06:06:11.652+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T06:06:11.679+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-25 06:06:11.105286+00:00
[2024-08-25T06:06:11.693+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=229) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T06:06:11.694+0000] {standard_task_runner.py:72} INFO - Started process 230 to run task
[2024-08-25T06:06:11.695+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_data_dag', 'run_python_script', 'manual__2024-08-25T06:06:11.105286+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpjwedzf7e']
[2024-08-25T06:06:11.699+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask run_python_script
[2024-08-25T06:06:11.776+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:11.105286+00:00 [running]> on host c252a95a8cff
[2024-08-25T06:06:11.923+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T06:06:11.105286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T06:06:11.105286+00:00'
[2024-08-25T06:06:11.924+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T06:06:11.940+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T06:06:11.942+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-25T06:06:11.960+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T06:06:13.911+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/customers.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.912+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/accounts.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.913+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transactions.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.915+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/branches.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.916+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/loans.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.917+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/credit_cards.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.918+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transaction_history.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.920+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/payment.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:13.921+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/investments.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:14.118+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T06:06:14.194+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T06:06:14.195+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_data_dag, task_id=run_python_script, run_id=manual__2024-08-25T06:06:11.105286+00:00, execution_date=20240825T060611, start_date=20240825T060611, end_date=20240825T060614
[2024-08-25T06:06:14.255+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T06:06:14.300+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T06:06:14.304+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
