[2024-08-26T07:45:34.038+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T07:45:34.071+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T07:45:32.706784+00:00 [queued]>
[2024-08-26T07:45:34.086+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T07:45:32.706784+00:00 [queued]>
[2024-08-26T07:45:34.087+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-26T07:45:34.122+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_data_generation_script> on 2024-08-26 07:45:32.706784+00:00
[2024-08-26T07:45:34.132+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2847) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T07:45:34.131+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_generation_dag', 'run_data_generation_script', 'manual__2024-08-26T07:45:32.706784+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dags.py', '--cfg-path', '/tmp/tmp2orsrwm2']
[2024-08-26T07:45:34.134+0000] {standard_task_runner.py:72} INFO - Started process 2848 to run task
[2024-08-26T07:45:34.134+0000] {standard_task_runner.py:105} INFO - Job 186: Subtask run_data_generation_script
[2024-08-26T07:45:34.197+0000] {task_command.py:467} INFO - Running <TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T07:45:32.706784+00:00 [running]> on host 7531b98fc8d7
[2024-08-26T07:45:34.385+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_generation_dag' AIRFLOW_CTX_TASK_ID='run_data_generation_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T07:45:32.706784+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T07:45:32.706784+00:00'
[2024-08-26T07:45:34.387+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T07:45:34.433+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-26T07:45:34.435+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/fake/Fake.py']
[2024-08-26T07:45:34.451+0000] {subprocess.py:86} INFO - Output:
[2024-08-26T07:45:49.155+0000] {subprocess.py:93} INFO - Data generation with errors completed.
[2024-08-26T07:45:49.197+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-26T07:45:49.238+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T07:45:49.239+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_generation_dag, task_id=run_data_generation_script, run_id=manual__2024-08-26T07:45:32.706784+00:00, execution_date=20240826T074532, start_date=20240826T074534, end_date=20240826T074549
[2024-08-26T07:45:49.287+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-26T07:45:49.315+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T07:45:49.317+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
