[2024-08-25T06:58:16.369+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T06:58:16.393+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:58:15.899550+00:00 [queued]>
[2024-08-25T06:58:16.414+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:58:15.899550+00:00 [queued]>
[2024-08-25T06:58:16.417+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T06:58:16.438+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-25 06:58:15.899550+00:00
[2024-08-25T06:58:16.447+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=224) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T06:58:16.449+0000] {standard_task_runner.py:72} INFO - Started process 225 to run task
[2024-08-25T06:58:16.447+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_data_dag', 'run_python_script', 'manual__2024-08-25T06:58:15.899550+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpz0o_vffd']
[2024-08-25T06:58:16.450+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask run_python_script
[2024-08-25T06:58:16.544+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:58:15.899550+00:00 [running]> on host dcedb42d949a
[2024-08-25T06:58:16.707+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T06:58:15.899550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T06:58:15.899550+00:00'
[2024-08-25T06:58:16.709+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T06:58:16.734+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T06:58:16.735+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-25T06:58:16.751+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T06:58:18.391+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/customers.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.392+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/accounts.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.392+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/transactions.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.393+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/branches.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.393+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/loans.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.394+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/credit_cards.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.394+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/transaction_history.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.395+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/payment.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.396+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào /home/lapthanh/Documents/DW_PROJECT/data/investments.csv: Cannot save file into a non-existent directory: '/home/lapthanh/Documents/DW_PROJECT/data'
[2024-08-25T06:58:18.547+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T06:58:18.587+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T06:58:18.589+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_data_dag, task_id=run_python_script, run_id=manual__2024-08-25T06:58:15.899550+00:00, execution_date=20240825T065815, start_date=20240825T065816, end_date=20240825T065818
[2024-08-25T06:58:18.641+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T06:58:18.684+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T06:58:18.691+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
