[2024-08-25T06:06:46.967+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T06:06:46.998+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:46.116198+00:00 [queued]>
[2024-08-25T06:06:47.012+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:46.116198+00:00 [queued]>
[2024-08-25T06:06:47.013+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T06:06:47.028+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-25 06:06:46.116198+00:00
[2024-08-25T06:06:47.037+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=244) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T06:06:47.038+0000] {standard_task_runner.py:72} INFO - Started process 245 to run task
[2024-08-25T06:06:47.037+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_data_dag', 'run_python_script', 'manual__2024-08-25T06:06:46.116198+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpamvkzxcv']
[2024-08-25T06:06:47.041+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask run_python_script
[2024-08-25T06:06:47.109+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:06:46.116198+00:00 [running]> on host c252a95a8cff
[2024-08-25T06:06:47.228+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T06:06:46.116198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T06:06:46.116198+00:00'
[2024-08-25T06:06:47.230+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T06:06:47.245+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T06:06:47.246+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-25T06:06:47.264+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T06:06:48.893+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/customers.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.894+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/accounts.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.895+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transactions.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.896+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/branches.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.898+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/loans.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.899+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/credit_cards.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.900+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transaction_history.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.901+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/payment.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:48.902+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/investments.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:06:49.067+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T06:06:49.115+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T06:06:49.116+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_data_dag, task_id=run_python_script, run_id=manual__2024-08-25T06:06:46.116198+00:00, execution_date=20240825T060646, start_date=20240825T060646, end_date=20240825T060649
[2024-08-25T06:06:49.147+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T06:06:49.182+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T06:06:49.184+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
