[2024-08-25T06:20:30.991+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T06:20:31.017+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:20:29.864201+00:00 [queued]>
[2024-08-25T06:20:31.031+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:20:29.864201+00:00 [queued]>
[2024-08-25T06:20:31.031+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T06:20:31.046+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-25 06:20:29.864201+00:00
[2024-08-25T06:20:31.055+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=429) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T06:20:31.056+0000] {standard_task_runner.py:72} INFO - Started process 430 to run task
[2024-08-25T06:20:31.054+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_data_dag', 'run_python_script', 'manual__2024-08-25T06:20:29.864201+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpl9c43v_0']
[2024-08-25T06:20:31.057+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask run_python_script
[2024-08-25T06:20:31.125+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:20:29.864201+00:00 [running]> on host c252a95a8cff
[2024-08-25T06:20:31.294+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T06:20:29.864201+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T06:20:29.864201+00:00'
[2024-08-25T06:20:31.295+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T06:20:31.312+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T06:20:31.313+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-25T06:20:31.334+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T06:20:32.917+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/customers.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.918+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/accounts.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.919+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transactions.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.921+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/branches.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.922+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/loans.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.923+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/credit_cards.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.924+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transaction_history.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.925+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/payment.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:32.926+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/investments.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:20:33.061+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T06:20:33.118+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T06:20:33.120+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_data_dag, task_id=run_python_script, run_id=manual__2024-08-25T06:20:29.864201+00:00, execution_date=20240825T062029, start_date=20240825T062031, end_date=20240825T062033
[2024-08-25T06:20:33.165+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T06:20:33.215+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T06:20:33.218+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
