[2024-08-25T06:09:55.706+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T06:09:55.728+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:09:54.616864+00:00 [queued]>
[2024-08-25T06:09:55.740+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:09:54.616864+00:00 [queued]>
[2024-08-25T06:09:55.741+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-25T06:09:55.755+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_python_script> on 2024-08-25 06:09:54.616864+00:00
[2024-08-25T06:09:55.764+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=314) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T06:09:55.766+0000] {standard_task_runner.py:72} INFO - Started process 315 to run task
[2024-08-25T06:09:55.764+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_data_dag', 'run_python_script', 'manual__2024-08-25T06:09:54.616864+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpx8chr559']
[2024-08-25T06:09:55.767+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask run_python_script
[2024-08-25T06:09:55.843+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_data_dag.run_python_script manual__2024-08-25T06:09:54.616864+00:00 [running]> on host c252a95a8cff
[2024-08-25T06:09:55.997+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_data_dag' AIRFLOW_CTX_TASK_ID='run_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T06:09:54.616864+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T06:09:54.616864+00:00'
[2024-08-25T06:09:55.998+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T06:09:56.014+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T06:09:56.016+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /spark/app/extract.py']
[2024-08-25T06:09:56.036+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T06:09:57.598+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/customers.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.600+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/accounts.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.601+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transactions.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.602+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/branches.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.604+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/loans.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.605+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/credit_cards.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.606+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/transaction_history.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.607+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/payment.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.608+0000] {subprocess.py:93} INFO - Lỗi khi lưu dữ liệu vào ./data/investments.csv: Cannot save file into a non-existent directory: 'data'
[2024-08-25T06:09:57.737+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T06:09:57.782+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T06:09:57.784+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_data_dag, task_id=run_python_script, run_id=manual__2024-08-25T06:09:54.616864+00:00, execution_date=20240825T060954, start_date=20240825T060955, end_date=20240825T060957
[2024-08-25T06:09:57.834+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T06:09:57.863+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T06:09:57.865+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
