[2024-08-26T01:08:29.896+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T01:08:29.934+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T01:08:29.946+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T01:08:29.947+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-26T01:08:29.964+0000] {taskinstance.py:2879} INFO - Executing <Task(SparkSubmitOperator): run_spark_job> on 2024-08-25 00:00:00+00:00
[2024-08-26T01:08:29.972+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=207) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T01:08:29.974+0000] {standard_task_runner.py:72} INFO - Started process 208 to run task
[2024-08-26T01:08:29.976+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_and_transform_dag', 'run_spark_job', 'scheduled__2024-08-25T00:00:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0srwvyzx']
[2024-08-26T01:08:29.980+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask run_spark_job
[2024-08-26T01:08:30.031+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_and_transform_dag.run_spark_job scheduled__2024-08-25T00:00:00+00:00 [running]> on host c3acd633df49
[2024-08-26T01:08:30.125+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_transform_dag' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T00:00:00+00:00'
[2024-08-26T01:08:30.126+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T01:08:30.156+0000] {base.py:84} INFO - Retrieving connection 'SPARK-PROJECT'
[2024-08-26T01:08:30.158+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --name spark_transform_job --deploy-mode client /app/transform.py
[2024-08-26T01:08:30.240+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2024-08-26T01:08:30.241+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2024-08-26T01:08:30.262+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --name spark_transform_job --deploy-mode client /app/transform.py. Error code is: 1.
[2024-08-26T01:08:30.291+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_and_transform_dag, task_id=run_spark_job, run_id=scheduled__2024-08-25T00:00:00+00:00, execution_date=20240825T000000, start_date=20240826T010829, end_date=20240826T010830
[2024-08-26T01:08:30.324+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T01:08:30.325+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 144 for task run_spark_job (Cannot execute: spark-submit --master spark://spark:7077 --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --name spark_transform_job --deploy-mode client /app/transform.py. Error code is: 1.; 208)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --name spark_transform_job --deploy-mode client /app/transform.py. Error code is: 1.
[2024-08-26T01:08:30.360+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-26T01:08:30.401+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T01:08:30.405+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
