[2024-08-26T04:34:23.231+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-26T04:34:23.265+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T04:34:22.363701+00:00 [queued]>
[2024-08-26T04:34:23.285+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T04:34:22.363701+00:00 [queued]>
[2024-08-26T04:34:23.286+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-08-26T04:34:23.306+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_data_generation_script> on 2024-08-26 04:34:22.363701+00:00
[2024-08-26T04:34:23.319+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=227) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-26T04:34:23.319+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_generation_dag', 'run_data_generation_script', 'manual__2024-08-26T04:34:22.363701+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/postgres_dags.py', '--cfg-path', '/tmp/tmppgagjf3d']
[2024-08-26T04:34:23.323+0000] {standard_task_runner.py:72} INFO - Started process 228 to run task
[2024-08-26T04:34:23.324+0000] {standard_task_runner.py:105} INFO - Job 166: Subtask run_data_generation_script
[2024-08-26T04:34:23.473+0000] {task_command.py:467} INFO - Running <TaskInstance: data_generation_dag.run_data_generation_script manual__2024-08-26T04:34:22.363701+00:00 [running]> on host f00445136288
[2024-08-26T04:34:23.617+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_generation_dag' AIRFLOW_CTX_TASK_ID='run_data_generation_script' AIRFLOW_CTX_EXECUTION_DATE='2024-08-26T04:34:22.363701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-26T04:34:22.363701+00:00'
[2024-08-26T04:34:23.619+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-26T04:34:23.641+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-26T04:34:23.642+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/fake/Fake.py']
[2024-08-26T04:34:23.659+0000] {subprocess.py:86} INFO - Output:
[2024-08-26T04:34:41.129+0000] {subprocess.py:93} INFO - Data generation with errors completed.
[2024-08-26T04:34:41.182+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-26T04:34:41.226+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-26T04:34:41.226+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_generation_dag, task_id=run_data_generation_script, run_id=manual__2024-08-26T04:34:22.363701+00:00, execution_date=20240826T043422, start_date=20240826T043423, end_date=20240826T043441
[2024-08-26T04:34:41.278+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-26T04:34:41.306+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-26T04:34:41.309+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
