[2024-08-25T13:21:57.472+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T13:21:57.497+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-25T13:16:51.260014+00:00 [queued]>
[2024-08-25T13:21:57.507+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-25T13:16:51.260014+00:00 [queued]>
[2024-08-25T13:21:57.508+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-25T13:21:57.522+0000] {taskinstance.py:2879} INFO - Executing <Task(SparkSubmitOperator): run_spark_job> on 2024-08-25 13:16:51.260014+00:00
[2024-08-25T13:21:57.531+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2031) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-25T13:21:57.532+0000] {standard_task_runner.py:72} INFO - Started process 2032 to run task
[2024-08-25T13:21:57.530+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_and_transform_dag', 'run_spark_job', 'manual__2024-08-25T13:16:51.260014+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpsbni5kmb']
[2024-08-25T13:21:57.532+0000] {standard_task_runner.py:105} INFO - Job 82: Subtask run_spark_job
[2024-08-25T13:21:57.593+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-25T13:16:51.260014+00:00 [running]> on host dcedb42d949a
[2024-08-25T13:21:57.763+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_transform_dag' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T13:16:51.260014+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-25T13:16:51.260014+00:00'
[2024-08-25T13:21:57.764+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T13:21:57.798+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2024-08-25T13:21:57.800+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf master=spark://172.18.0.3:7077 --name spark_transform_job --queue root.default /app/transform.py
[2024-08-25T13:21:57.869+0000] {spark_submit.py:579} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-08-25T13:21:57.872+0000] {spark_submit.py:579} INFO - JAVA_HOME is not set
[2024-08-25T13:21:57.895+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf master=spark://172.18.0.3:7077 --name spark_transform_job --queue root.default /app/transform.py. Error code is: 1.
[2024-08-25T13:21:57.903+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_and_transform_dag, task_id=run_spark_job, run_id=manual__2024-08-25T13:16:51.260014+00:00, execution_date=20240825T131651, start_date=20240825T132157, end_date=20240825T132157
[2024-08-25T13:21:57.922+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T13:21:57.923+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 82 for task run_spark_job (Cannot execute: spark-submit --master yarn --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf master=spark://172.18.0.3:7077 --name spark_transform_job --queue root.default /app/transform.py. Error code is: 1.; 2032)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf spark.executor.extraClassPath=/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar --conf master=spark://172.18.0.3:7077 --name spark_transform_job --queue root.default /app/transform.py. Error code is: 1.
[2024-08-25T13:21:57.959+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-25T13:21:57.986+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T13:21:57.988+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
