[2024-08-27T08:41:13.981+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-27T08:41:14.005+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-27T08:31:05.266970+00:00 [queued]>
[2024-08-27T08:41:14.017+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-27T08:31:05.266970+00:00 [queued]>
[2024-08-27T08:41:14.018+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-27T08:41:14.032+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): run_spark_job> on 2024-08-27 08:31:05.266970+00:00
[2024-08-27T08:41:14.041+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8859) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-27T08:41:14.042+0000] {standard_task_runner.py:72} INFO - Started process 8860 to run task
[2024-08-27T08:41:14.043+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_and_transform_dag', 'run_spark_job', 'manual__2024-08-27T08:31:05.266970+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Dags.py', '--cfg-path', '/tmp/tmpy2ul6uh0']
[2024-08-27T08:41:14.048+0000] {standard_task_runner.py:105} INFO - Job 204: Subtask run_spark_job
[2024-08-27T08:41:14.134+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_and_transform_dag.run_spark_job manual__2024-08-27T08:31:05.266970+00:00 [running]> on host 6ac8cf047f5e
[2024-08-27T08:41:14.286+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_and_transform_dag' AIRFLOW_CTX_TASK_ID='run_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-08-27T08:31:05.266970+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-27T08:31:05.266970+00:00'
[2024-08-27T08:41:14.287+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-27T08:41:14.304+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-27T08:41:14.317+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec e9392c7cc91a /opt/bitnami/spark/bin/spark-submit --master spark://spark:7077 --jars /opt/bitnami/spark/jars/snowflake-jdbc-3.16.1.jar,/opt/bitnami/spark/jars/spark-snowflake_2.12-2.16.0-spark_3.2.jar /app/transform.py']
[2024-08-27T08:41:14.340+0000] {subprocess.py:86} INFO - Output:
[2024-08-27T08:41:14.381+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-08-27T08:41:14.384+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-08-27T08:41:14.403+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-27T08:41:14.410+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_and_transform_dag, task_id=run_spark_job, run_id=manual__2024-08-27T08:31:05.266970+00:00, execution_date=20240827T083105, start_date=20240827T084114, end_date=20240827T084114
[2024-08-27T08:41:14.446+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-27T08:41:14.447+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 204 for task run_spark_job (Bash command failed. The command returned a non-zero exit code 1.; 8860)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-08-27T08:41:14.511+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-27T08:41:14.560+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-27T08:41:14.564+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
